// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjhhdkqxukfgvinmwwgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qaGhka3F4dWtmZ3Zpbm13d2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDMwNzksImV4cCI6MjA2NTUxOTA3OX0.mKTZErb6O5USQPOwHewrRgofQH5Dm0cuRagdep2zbfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);